env:
  global:
    - NODE_VERSION=6.1

language: android

jdk: oraclejdk8

android:
  components:
    - platform-tools
    - build-tools-23.0.1
    - android-23
    - extra-android-m2repository
    - sys-img-armeabi-v7a-android-19

before_cache:
    - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock

cache:
    directories:
        - .nvm
        - $HOME/.gradle/caches/
        - $HOME/.gradle/wrapper/

install:
    - nvm install $NODE_VERSION
    - npm install

script:
    - npm run tslint
    - tns build android

#notifications:
#  email:
#    - leban.rene@gmail.com
#    - jens.sproede@gmail.com
